target:
  host: plexdev.azurecr.io
  repository: pcp
sources:
- repository: openpolicyagent/gatekeeper
  tag: v3.1.0-beta.10
- repository: jettech/kube-webhook-certgen
  tag: v1.2.0
- repository: kubernetes-ingress-controller/nginx-ingress-controller
  host: quay.io
  tag: 0.32.0
- repository: coredns
  host: k8s.gcr.io
  tag: 1.6.2
- repository: etcd
  host: k8s.gcr.io
  tag: 3.3.15-0
- repository: kindest/kindnetd
  tag: 0.5.3
- repository: kube-apiserver
  host: k8s.gcr.io
  tag: v1.16.3
- repository: kube-controller-manager
  host: k8s.gcr.io
  tag: v1.16.3
- repository: kube-proxy
  host: k8s.gcr.io
  tag: v1.16.3
- repository: kube-scheduler
  host: k8s.gcr.io
  tag: v1.16.3
- repository: prom/alertmanager
  tag: v0.21.0
- repository: jimmidyson/configmap-reload
  tag: v0.4.0
- repository: coreos/kube-state-metrics
  host: quay.io
  tag: v1.9.5
- repository: prom/node-exporter
  tag: v0.18.1
- repository: coreos/prometheus-operator
  host: quay.io
  tag: v0.40.0
- repository: prom/prometheus
  tag: v2.19.2
- repository: coreos/prometheus-config-reloader
  host: quay.io
  tag: v0.40.0
- repository: grafana/promtail
  tag: v0.4.0
