name: Pull Request
on: [pull_request]

jobs:
  go-tests:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.4'

      - name: checkout source
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: unit tests
        run: go test -v ./...

      - name: build
        run: go build -o sinker main.go
